version: '3.8'

services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always
    networks:
      - app
    container_name: frontend

  backend:
    build: backend
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - app
    container_name: backend
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://fastapi_emad:fastapi_emad@db:5432/project1
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - app
    environment:
      - POSTGRES_USER=fastapi_emad
      - POSTGRES_PASSWORD=fastapi_emad
      - POSTGRES_DB=project1
networks:
  app:
    driver: bridge
volumes:
  postgres_data: